# Generated by Django 5.2.7 on 2025-10-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('reminder', '掛號提醒'), ('open_slots', '開放未來掛號'), ('daily_report', '每日報表'), ('backup', '資料備份')], max_length=50)),
                ('status', models.CharField(choices=[('pending', '執行中'), ('success', '成功'), ('failed', '失敗')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系統作業紀錄',
                'verbose_name_plural': '系統作業紀錄',
                'ordering': ['-started_at'],
            },
        ),
    ]
