# Generated by Django 5.2.7 on 2025-10-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='科別代碼')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科別名稱')),
                ('description', models.TextField(blank=True, verbose_name='介紹')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '科別',
                'verbose_name_plural': '科別',
                'ordering': ['name'],
            },
        ),
    ]
