# Generated by Django 5.2.7 on 2025-10-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', '已預約'), ('checked_in', '已報到'), ('in_progress', '看診中'), ('completed', '已完成'), ('cancelled', '已取消')], default='reserved', max_length=20)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.familymember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'verbose_name': '掛號',
                'verbose_name_plural': '掛號',
                'ordering': ['schedule', 'queue_number'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('booked', '預約'), ('checked_in', '報到'), ('called', '叫號'), ('completed', '完成'), ('cancelled', '取消'), ('system', '系統事件')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registrations.appointment')),
            ],
            options={
                'verbose_name': '掛號事件紀錄',
                'verbose_name_plural': '掛號事件紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30, unique=True, verbose_name='醫師證書號')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='職稱')),
                ('specialties', models.CharField(blank=True, max_length=255, verbose_name='專長')),
                ('bio', models.TextField(blank=True, verbose_name='簡介')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='clinics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '醫師',
                'verbose_name_plural': '醫師',
                'ordering': ['department__name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午'), ('evening', '夜間')], max_length=20)),
                ('clinic_room', models.CharField(blank=True, max_length=20, verbose_name='診間')),
                ('quota', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('open', '可掛號'), ('closed', '已額滿'), ('paused', '暫停掛號'), ('ended', '看診結束')], default='open', max_length=20)),
                ('open_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='registrations.doctor')),
            ],
            options={
                'verbose_name': '班表',
                'verbose_name_plural': '班表',
                'ordering': ['date', 'session'],
                'unique_together': {('doctor', 'date', 'session')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='registrations.doctorschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('schedule', 'queue_number')},
        ),
    ]
