# Generated by Django 5.2.7 on 2025-10-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='身分證號')),
                ('medical_record_number', models.CharField(max_length=20, unique=True, verbose_name='病歷號')),
                ('birth_date', models.DateField(verbose_name='生日')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='緊急聯絡人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '病患',
                'verbose_name_plural': '病患',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('relationship', models.CharField(max_length=50, verbose_name='關係')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='身分證/護照')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patient')),
            ],
            options={
                'verbose_name': '家屬',
                'verbose_name_plural': '家屬',
                'unique_together': {('patient', 'full_name', 'relationship')},
            },
        ),
    ]
